import RequestProject.ExpSharpestData0
import RequestProject.ExpSharpestData1
import RequestProject.ExpSharpestData2
import RequestProject.ExpSharpestData3
import RequestProject.ExpSharpestData4
import RequestProject.ExpSharpestData5
import RequestProject.ExpSharpestData6
import RequestProject.ExpSharpestData7
import RequestProject.ExpSharpestData8

/-!
# Certificate data at length 16 (round 10, T31)

A multiplicity certificate at `lam = 3/2`: 2008 cells tiling
`J = [1/6, 5/6]`, each carrying `49` distinct branch words of length `16`
whose images lie again in `J`.  Generated by `scripts/gen_expsharpest.py`; the
checks live in `RequestProject.ExpSharpest`.

The data itself is split across `RequestProject.ExpSharpestData0` …
`RequestProject.ExpSharpestData8`; this file only assembles it.
-/

namespace KnotGame
namespace ExpSharpest

open KnotGame.ExpMultiCert

/-- The certificate: 2008 cells, each with 49 words of length 16. -/
def cells : List MCell :=
  cellsG0 ++ cellsG1 ++ cellsG2 ++ cellsG3 ++ cellsG4 ++ cellsG5 ++ cellsG6 ++ cellsG7 ++ cellsG8 ++ cellsG9 ++ cellsG10 ++ cellsG11 ++ cellsG12 ++ cellsG13 ++ cellsG14 ++ cellsG15 ++ cellsG16 ++ cellsG17 ++ cellsG18 ++ cellsG19 ++ cellsG20 ++ cellsG21 ++ cellsG22 ++ cellsG23 ++ cellsG24 ++ cellsG25 ++ cellsG26 ++ cellsG27 ++ cellsG28 ++ cellsG29 ++ cellsG30 ++ cellsG31 ++ cellsG32 ++ cellsG33 ++ cellsG34 ++ cellsG35 ++ cellsG36 ++ cellsG37 ++ cellsG38 ++ cellsG39 ++ cellsG40

end ExpSharpest
end KnotGame
