import RequestProject.ExpAboveData0
import RequestProject.ExpAboveData1
import RequestProject.ExpAboveData2
import RequestProject.ExpAboveData3
import RequestProject.ExpAboveData4
import RequestProject.ExpAboveData5
import RequestProject.ExpAboveData6
import RequestProject.ExpAboveData7
import RequestProject.ExpAboveData8
import RequestProject.ExpAboveData9
import RequestProject.ExpAboveData10
import RequestProject.ExpAboveData11

/-!
# Certificate data above the golden ratio (round 10, T32)

A variable-return-time doubling certificate for `J = [43/100, 57/100]`, valid
uniformly over the parameter window `lam ∈ [3457/2000, 4331/2500]`, which lies
above the golden ratio and contains `√3`:
180 parameter cells carrying 17141 point cells in all, each with two
diverging branch words of length at most 18.  Generated by
`scripts/gen_expabove.py`; the checks live in
`RequestProject.ExpAboveChecks` and the conclusions in `RequestProject.ExpAbove`.

The data itself is split across `RequestProject.ExpAboveData0` …
`RequestProject.ExpAboveData11`; this file only assembles it.
-/

namespace KnotGame
namespace ExpAbove

open KnotGame.ExpVar

/-- The certificate: 180 parameter cells, in increasing order. -/
def pcells : List VLamCell :=
  pcellsG0 ++ pcellsG1 ++ pcellsG2 ++ pcellsG3 ++ pcellsG4 ++ pcellsG5 ++ pcellsG6 ++ pcellsG7 ++ pcellsG8 ++ pcellsG9 ++ pcellsG10 ++ pcellsG11 ++ pcellsG12 ++ pcellsG13 ++ pcellsG14 ++ pcellsG15 ++ pcellsG16 ++ pcellsG17 ++ pcellsG18 ++ pcellsG19 ++ pcellsG20 ++ pcellsG21 ++ pcellsG22 ++ pcellsG23 ++ pcellsG24 ++ pcellsG25 ++ pcellsG26 ++ pcellsG27 ++ pcellsG28 ++ pcellsG29 ++ pcellsG30 ++ pcellsG31 ++ pcellsG32 ++ pcellsG33 ++ pcellsG34 ++ pcellsG35

end ExpAbove
end KnotGame
