import RequestProject.ExpAboveData

/-!
# Kernel checks for the certificate above the golden ratio (round 10, T32)

Every check below is a kernel reduction over exact rationals (`decide +kernel`).
The certificate is checked group by group — 36 groups of at most 5
parameter cells — since a single reduction over the whole list does not go
through.  Generated by `scripts/gen_expabove.py`.
-/

namespace KnotGame
namespace ExpAbove

open KnotGame.ExpCert KnotGame.ExpVar

set_option maxHeartbeats 4000000

/-- The return-time bound certified below. -/
abbrev Tbound : ℕ := 18

/-- The check of one group of parameter cells. -/
abbrev Q : VLamCell → Bool := vlamCellOK (43/100) (57/100) Tbound

/-- The parameter cells tile the window. -/
lemma pcells_chained : chained (3457/2000) pcells (4331/2500) = true := by
  decide +kernel

lemma pcellsG0_ok : pcellsG0.all Q = true := by decide +kernel
lemma pcellsG1_ok : pcellsG1.all Q = true := by decide +kernel
lemma pcellsG2_ok : pcellsG2.all Q = true := by decide +kernel
lemma pcellsG3_ok : pcellsG3.all Q = true := by decide +kernel
lemma pcellsG4_ok : pcellsG4.all Q = true := by decide +kernel
lemma pcellsG5_ok : pcellsG5.all Q = true := by decide +kernel
lemma pcellsG6_ok : pcellsG6.all Q = true := by decide +kernel
lemma pcellsG7_ok : pcellsG7.all Q = true := by decide +kernel
lemma pcellsG8_ok : pcellsG8.all Q = true := by decide +kernel
lemma pcellsG9_ok : pcellsG9.all Q = true := by decide +kernel
lemma pcellsG10_ok : pcellsG10.all Q = true := by decide +kernel
lemma pcellsG11_ok : pcellsG11.all Q = true := by decide +kernel
lemma pcellsG12_ok : pcellsG12.all Q = true := by decide +kernel
lemma pcellsG13_ok : pcellsG13.all Q = true := by decide +kernel
lemma pcellsG14_ok : pcellsG14.all Q = true := by decide +kernel
lemma pcellsG15_ok : pcellsG15.all Q = true := by decide +kernel
lemma pcellsG16_ok : pcellsG16.all Q = true := by decide +kernel
lemma pcellsG17_ok : pcellsG17.all Q = true := by decide +kernel
lemma pcellsG18_ok : pcellsG18.all Q = true := by decide +kernel
lemma pcellsG19_ok : pcellsG19.all Q = true := by decide +kernel
lemma pcellsG20_ok : pcellsG20.all Q = true := by decide +kernel
lemma pcellsG21_ok : pcellsG21.all Q = true := by decide +kernel
lemma pcellsG22_ok : pcellsG22.all Q = true := by decide +kernel
lemma pcellsG23_ok : pcellsG23.all Q = true := by decide +kernel
lemma pcellsG24_ok : pcellsG24.all Q = true := by decide +kernel
lemma pcellsG25_ok : pcellsG25.all Q = true := by decide +kernel
lemma pcellsG26_ok : pcellsG26.all Q = true := by decide +kernel
lemma pcellsG27_ok : pcellsG27.all Q = true := by decide +kernel
lemma pcellsG28_ok : pcellsG28.all Q = true := by decide +kernel
lemma pcellsG29_ok : pcellsG29.all Q = true := by decide +kernel
lemma pcellsG30_ok : pcellsG30.all Q = true := by decide +kernel
lemma pcellsG31_ok : pcellsG31.all Q = true := by decide +kernel
lemma pcellsG32_ok : pcellsG32.all Q = true := by decide +kernel
lemma pcellsG33_ok : pcellsG33.all Q = true := by decide +kernel
lemma pcellsG34_ok : pcellsG34.all Q = true := by decide +kernel
lemma pcellsG35_ok : pcellsG35.all Q = true := by decide +kernel

lemma pcells_ok : pcells.all Q = true := by
  simp only [pcells, List.all_append, pcellsG0_ok, pcellsG1_ok, pcellsG2_ok, pcellsG3_ok, pcellsG4_ok, pcellsG5_ok, pcellsG6_ok, pcellsG7_ok, pcellsG8_ok, pcellsG9_ok, pcellsG10_ok, pcellsG11_ok, pcellsG12_ok, pcellsG13_ok, pcellsG14_ok, pcellsG15_ok, pcellsG16_ok, pcellsG17_ok, pcellsG18_ok, pcellsG19_ok, pcellsG20_ok, pcellsG21_ok, pcellsG22_ok, pcellsG23_ok, pcellsG24_ok, pcellsG25_ok, pcellsG26_ok, pcellsG27_ok, pcellsG28_ok, pcellsG29_ok, pcellsG30_ok, pcellsG31_ok, pcellsG32_ok, pcellsG33_ok, pcellsG34_ok, pcellsG35_ok, Bool.and_self]

end ExpAbove
end KnotGame
