import RequestProject.PlasticConfig

/-!
# The orbit of `1/2` at the plastic number has exactly `153` points

`PlasticOrbit.lean` certifies that the forward orbit of `1/2` along surviving
branches is *contained* in the explicit `153`-point list `orbitList`.  Here we
certify the converse: every listed point is attained.  The certificate
`orbCert` records, for each orbit index, its distance from `1/2` in the
automaton of `PlasticIndex.lean` together with a move and a predecessor index
realising it; `chk_orb` checks all `153` records by kernel computation.

Consequently `Orb ρ` is exactly the set of listed points, and it has `153`
elements (`card_Orb_rho`) — the first clause of Proposition 9.
-/

namespace KnotGame
namespace Plastic

set_option maxRecDepth 100000

/-- For each orbit index: its distance from `1/2`, the move producing it, and
the index it is produced from.  Generated by `scripts/plastic_orbcert.py`. -/
def orbCert : List (ℕ × ℕ × ℕ) :=
  [(8,0,39), (9,1,0), (10,1,1), (4,0,41), (14,0,42), (5,1,3), (23,0,44), (15,1,4), (6,0,45),
  (24,1,6), (16,1,7), (19,0,46), (7,1,8), (11,0,48), (10,0,49), (20,1,11), (8,1,12), (12,0,51),
  (11,1,14), (21,1,15), (2,0,52), (13,1,17), (11,0,53), (5,0,54), (8,0,55), (20,0,56), (3,1,20),
  (7,0,58), (12,1,22), (6,1,23), (8,0,60), (9,1,24), (12,0,61), (21,1,25), (4,1,26), (17,0,63),
  (9,0,64), (8,1,27), (13,1,28), (7,1,29), (9,1,30), (3,0,69), (13,1,32), (18,0,70), (22,1,33),
  (5,1,34), (18,1,35), (6,0,72), (10,1,36), (9,1,37), (7,0,74), (11,0,75), (1,0,76), (10,1,40),
  (4,1,41), (7,0,78), (19,1,43), (9,0,79), (6,1,45), (5,0,81), (7,1,47), (11,1,48), (3,0,83),
  (16,0,84), (8,1,50), (14,0,85), (12,1,51), (13,0,86), (15,0,87), (2,1,52), (17,0,89),
  (4,0,90), (5,1,54), (8,1,55), (6,0,93), (10,1,57), (0,0,0), (10,0,95), (6,2,59), (8,2,60),
  (5,0,98), (4,2,62), (17,2,63), (2,0,100), (15,2,65), (13,2,66), (12,0,101), (14,2,67),
  (8,0,102), (16,2,68), (3,2,69), (11,0,104), (7,0,105), (5,2,71), (6,2,72), (9,2,73),
  (19,0,109), (7,2,74), (4,0,111), (10,0,112), (1,2,76), (11,2,77), (7,2,78), (9,2,79),
  (10,0,116), (6,2,80), (18,0,117), (5,0,118), (22,0,119), (18,2,82), (13,0,120), (3,2,83),
  (9,0,122), (7,0,123), (13,2,86), (8,0,125), (9,2,88), (17,2,89), (4,2,90), (21,0,127),
  (12,2,91), (9,0,128), (8,2,92), (6,2,93), (12,0,130), (7,2,94), (3,0,132), (20,2,96),
  (8,2,97), (5,2,98), (11,2,99), (13,0,135), (2,2,100), (21,0,137), (11,0,138), (12,2,101),
  (8,0,140), (20,0,141), (10,2,103), (11,2,104), (7,0,144), (19,2,106), (16,0,145), (24,0,146),
  (6,2,107), (15,0,148), (23,2,108), (5,0,149), (14,2,110), (4,2,111), (10,0,151), (9,0,152),
  (8,2,113)]

/-- The recorded distance of an orbit index from `1/2`. -/
def odep (i : ℕ) : ℕ := (orbCert.getD i (0, 0, 0)).1

/-- The recorded move producing an orbit index. -/
def omv (i : ℕ) : ℕ := (orbCert.getD i (0, 0, 0)).2.1

/-- The recorded predecessor of an orbit index. -/
def opar (i : ℕ) : ℕ := (orbCert.getD i (0, 0, 0)).2.2

/-- The check: `1/2` is at distance `0`, and every other index is the image of
its recorded predecessor, which is one step closer. -/
def orbChk : Bool :=
  (List.range 153).all (fun i =>
    if i = halfIdx then decide (odep i = 0)
    else decide (opar i < 153) && decide (odep (opar i) + 1 = odep i) &&
      decide (tget (tabOf (moveOf (omv i))) (opar i) = i))

theorem chk_orb : orbChk = true := by decide +kernel

lemma orbChk_at {i : ℕ} (hi : i < 153) :
    (if i = halfIdx then decide (odep i = 0)
      else decide (opar i < 153) && decide (odep (opar i) + 1 = odep i) &&
        decide (tget (tabOf (moveOf (omv i))) (opar i) = i)) = true :=
  List.all_eq_true.1 chk_orb i (List.mem_range.2 hi)

/-- Every listed orbit point is attained by a run of the game. -/
lemma mem_Orb_oget : ∀ (n i : ℕ), i < 153 → odep i ≤ n → tval (oget i) ∈ Orb rho := by
  intro n
  induction n with
  | zero =>
      intro i hi hd
      have hchk := orbChk_at hi
      by_cases hhalf : i = halfIdx
      · subst hhalf
        exact ⟨[], trivial, by rw [posAfter_nil, tval_oget_halfIdx]⟩
      · rw [if_neg hhalf] at hchk
        simp only [Bool.and_eq_true, decide_eq_true_eq] at hchk
        omega
  | succ n ih =>
      intro i hi hd
      by_cases hhalf : i = halfIdx
      · subst hhalf
        exact ⟨[], trivial, by rw [posAfter_nil, tval_oget_halfIdx]⟩
      · have hchk := orbChk_at hi
        rw [if_neg hhalf] at hchk
        simp only [Bool.and_eq_true, decide_eq_true_eq] at hchk
        obtain ⟨⟨hpar, hdep⟩, htget⟩ := hchk
        obtain ⟨w, hw, hpos⟩ := ih (opar i) hpar (by omega)
        have h255 : tget (tabOf (moveOf (omv i))) (opar i) ≠ 255 := by
          rw [htget]; omega
        have hsurv : survives rho (moveOf (omv i)) (tval (oget (opar i))) := by
          by_contra hc
          exact h255 ((tget_eq_255_iff hpar).2 hc)
        refine ⟨w ++ [moveOf (omv i)], ?_, ?_⟩
        · rw [survivesWord_append, hpos]
          exact ⟨hw, hsurv, trivial⟩
        · rw [posAfter_append, hpos]
          simp only [posAfter_cons, posAfter_nil]
          rw [← oget_tget hpar h255, htget]

lemma posAfter_mem_OrbSet : ∀ (w : List Move) (x : ℝ), x ∈ OrbSet →
    survivesWord rho x w → posAfter rho x w ∈ OrbSet
  | [], x, hx, _ => hx
  | m :: w, x, hx, hs => by
      rw [survivesWord_cons] at hs
      exact posAfter_mem_OrbSet w _ (OrbSet_closed x hx m hs.1) hs.2

/-- **The orbit is exactly the listed set.** -/
theorem Orb_rho_eq_OrbSet : Orb rho = OrbSet := by
  apply Set.eq_of_subset_of_subset
  · rintro x ⟨w, hw, rfl⟩
    exact posAfter_mem_OrbSet w _ half_mem_OrbSet hw
  · rintro x ⟨t, ht, rfl⟩
    obtain ⟨i, hi, hti⟩ := List.mem_iff_getElem.1 ht
    have hlen : orbitList.length = 153 := orbitList_length
    have hi' : i < 153 := by omega
    have hoget : oget i = t := by
      rw [oget, List.getD_eq_getElem _ _ hi, hti]
    rw [← hoget]
    exact mem_Orb_oget (odep i) i hi' le_rfl

lemma tval_inj_on_orbitList {t s : Tri} (ht : t ∈ orbitList) (hs : s ∈ orbitList)
    (h : tval t = tval s) : t = s := by
  by_contra hne
  have hd := orbitList_pairwise.forall (fun a b hab => by rwa [abs_sub_comm]) ht hs hne
  rw [h, sub_self, abs_zero] at hd
  linarith [deltaRho_pos]

/-- **Proposition 9, first clause.**  The orbit of `1/2` at the plastic number
has exactly `153` points. -/
theorem card_Orb_rho : (Orb rho).ncard = 153 := by
  classical
  have hnd : (orbitList.map tval).Nodup := by
    refine List.Nodup.map_on ?_ ?_
    · intro a ha b hb hab
      exact tval_inj_on_orbitList ha hb hab
    · refine orbitList_pairwise.imp ?_
      intro a b hab hne
      rw [hne, sub_self, abs_zero] at hab
      linarith [deltaRho_pos]
  have hset : Orb rho = ((orbitList.map tval).toFinset : Set ℝ) := by
    rw [Orb_rho_eq_OrbSet]
    ext x
    simp only [OrbSet, Set.mem_setOf_eq, Finset.mem_coe, List.mem_toFinset, List.mem_map]
  rw [hset, Set.ncard_coe_finset, List.toFinset_card_of_nodup hnd, List.length_map,
    orbitList_length]

end Plastic
end KnotGame
