"""Generate RequestProject/ExpSharperData.lean: a sharper multiplicity
certificate at lam = 3/2 (round 10, target T31).

Usage:  python3 scripts/gen_expsharper.py T k [a_num a_den b_num b_den]

Round 7 certified 15 words of length 12 on J = [1/4,3/4] (rate 15^(1/12) =
1.25316).  With the faster search of `scripts/expcert_dfs.py` the default here
is 26 words of length 14 on J = [1/6,5/6] (rate 26^(1/14) = 1.26203).

Nothing about this program is trusted: the Lean kernel re-checks its output in
RequestProject/ExpSharper.lean.
"""
from fractions import Fraction as F
import sys

sys.path.insert(0, "scripts")
from expcert_dfs import greedy, fq, fw  # noqa: E402


def main():
    T = int(sys.argv[1]) if len(sys.argv) > 1 else 14
    k = int(sys.argv[2]) if len(sys.argv) > 2 else 26
    if len(sys.argv) > 3:
        a = F(int(sys.argv[3]), int(sys.argv[4]))
        b = F(int(sys.argv[5]), int(sys.argv[6]))
    else:
        a, b = F(1, 6), F(5, 6)
    lam = F(3, 2)
    cells = greedy(T, a, b, k, lam, lam)
    if cells is None:
        print("no certificate", file=sys.stderr)
        sys.exit(1)
    print(f"-- T = {T}, k = {k}, J = [{a},{b}], {len(cells)} cells", file=sys.stderr)

    out = []
    out.append("import RequestProject.ExpMultiCert")
    out.append("")
    out.append("/-!")
    out.append("# Certificate data for the sharper bound at `lam = 3/2` (round 10, T31)")
    out.append("")
    out.append(f"A multiplicity certificate at `lam = 3/2`: {len(cells)} cells tiling")
    out.append(f"`J = [{a}, {b}]`, each carrying `{k}` distinct branch words of length `{T}`")
    out.append("whose images lie again in `J`.  Generated by `scripts/gen_expsharper.py`; the")
    out.append("checks live in `RequestProject.ExpSharper`.")
    out.append("-/")
    out.append("")
    out.append("namespace KnotGame")
    out.append("namespace ExpSharper")
    out.append("")
    out.append("open KnotGame.ExpMultiCert")
    out.append("")
    out.append("-- The cell list is a large literal; elaborating it exceeds the default budget.")
    out.append("set_option maxHeartbeats 4000000")
    out.append("")
    for i, (p, q, ws) in enumerate(cells):
        body = ", ".join(fw(w) for w in ws)
        out.append(f"/-- Cell {i} of the certificate. -/")
        out.append(f"def cell{i} : MCell := ({fq(p)}, {fq(q)}, [{body}])")
        out.append("")
    G = 50
    groups = [list(range(i, min(i + G, len(cells)))) for i in range(0, len(cells), G)]
    for gi, idx in enumerate(groups):
        out.append(f"/-- Group {gi} of the certificate (cells {idx[0]}–{idx[-1]}). -/")
        out.append(f"def cellsG{gi} : List MCell :=")
        out.append("  [" + ", ".join(f"cell{i}" for i in idx) + "]")
        out.append("")
    out.append(f"/-- The certificate: {len(cells)} cells, each with {k} words of length {T}. -/")
    out.append("def cells : List MCell :=")
    out.append("  " + " ++ ".join(f"cellsG{gi}" for gi in range(len(groups))))
    out.append("")
    out.append(f"/-- The number of groups: {len(groups)}. -/")
    out.append(f"def numGroups : ℕ := {len(groups)}")
    out.append("")
    out.append("end ExpSharper")
    out.append("end KnotGame")
    open("RequestProject/ExpSharperData.lean", "w").write("\n".join(out) + "\n")


main()
