"""Generate the round-10 T32 certificate: a variable-return-time doubling
certificate on a rational parameter window ABOVE the golden ratio containing √3.

Usage:  python3 scripts/gen_expabove.py L0num L0den L1num L1den Tmax nparam group
        [Anum Aden Bnum Bden]

Writes `RequestProject/ExpAboveData0.lean` ... (the data, split across several
files so that no single file is too large to elaborate), the umbrella file
`RequestProject/ExpAboveData.lean` and
`RequestProject/ExpAboveChecks.lean` (the kernel checks, grouped).  The window
`[L0, L1]` is split into `nparam` parameter cells of equal width; each is then
split further, adaptively, until a certificate is found.  On each parameter cell
a chained list of point cells tiles `J = [2/5, 3/5]`, and every cell carries two
*diverging* branch words of length at most `Tmax` whose enclosures — computed
with interval arithmetic in the parameter as well as in the point — return to
`J`.

Nothing about this program is trusted: the Lean kernel re-checks every cell.
"""
from fractions import Fraction as F
import sys

sys.path.insert(0, "scripts")
from expvar_search import cover, fq, fw  # noqa: E402

A, B = F(43, 100), F(57, 100)


def main():
    L0 = F(int(sys.argv[1]), int(sys.argv[2]))
    L1 = F(int(sys.argv[3]), int(sys.argv[4]))
    Tmax = int(sys.argv[5])
    N = int(sys.argv[6])
    G = int(sys.argv[7]) if len(sys.argv) > 7 else 5
    global A, B
    if len(sys.argv) > 8:
        A = F(int(sys.argv[8]), int(sys.argv[9]))
        B = F(int(sys.argv[10]), int(sys.argv[11]))

    res = []
    for i in range(N):
        D = 10 ** 7
        l0 = L0 if i == 0 else F(int((L0 + (L1 - L0) * F(i, N)) * D), D)
        l1 = L1 if i == N - 1 else F(int((L0 + (L1 - L0) * F(i + 1, N)) * D), D)
        r = cover(l0, l1, Tmax, A, B, maxdepth=6)
        if r is None:
            print("FAILED on", float(l0), float(l1), file=sys.stderr)
            sys.exit(1)
        res += r
        print("done", i, len(r), sum(len(c) for _, _, c in r), file=sys.stderr)
        sys.stderr.flush()

    total = sum(len(c) for _, _, c in res)
    used = max(max(len(u), len(v)) for _, _, c in res for _, _, u, v in c)
    letters = sum(len(u) + len(v) for _, _, c in res for _, _, u, v in c)
    print(f"-- parameter cells: {len(res)}, point cells: {total}, "
          f"max word length: {used}, letters: {letters}", file=sys.stderr)

    groups = [list(range(i, min(i + G, len(res)))) for i in range(0, len(res), G)]
    H = 3  # groups per data file
    chunks = [groups[i:i + H] for i in range(0, len(groups), H)]

    def header(mod, extra):
        h = []
        h.append("import RequestProject.ExpVar")
        h.append("")
        h.append("/-!")
        h.append(f"# {mod}")
        h.append("")
        h += extra
        h.append("-/")
        h.append("")
        h.append("namespace KnotGame")
        h.append("namespace ExpAbove")
        h.append("")
        h.append("open KnotGame.ExpCert KnotGame.ExpVar")
        h.append("")
        h.append("-- The cell lists are large literals; elaborating them exceeds the default budget.")
        h.append("set_option maxHeartbeats 4000000")
        h.append("")
        return h

    blurb = [
        f"A variable-return-time doubling certificate for `J = [{fq(A)}, {fq(B)}]`, valid",
        f"uniformly over the parameter window `lam ∈ [{fq(L0)}, {fq(L1)}]`, which lies",
        "above the golden ratio and contains `√3`:",
        f"{len(res)} parameter cells carrying {total} point cells in all, each with two",
        f"diverging branch words of length at most {used}.  Generated by",
        "`scripts/gen_expabove.py`; the checks live in",
        "`RequestProject.ExpAboveChecks` and the conclusions in `RequestProject.ExpAbove`.",
    ]

    for ci, chunk in enumerate(chunks):
        lo, hi = chunk[0][0], chunk[-1][-1]
        out = header(
            f"Certificate data above the golden ratio, part {ci} (round 10, T32)",
            blurb + ["", f"This file carries parameter cells {lo}–{hi} of the certificate."])
        for idx in chunk:
            for i in idx:
                l0, l1, cells = res[i]
                out.append(f"/-- Parameter cell {i}: `lam ∈ [{fq(l0)}, {fq(l1)}]`. -/")
                out.append(f"def pcell{i} : VLamCell :=")
                out.append(f"  ({fq(l0)}, {fq(l1)},")
                for j, (p, q, u, v) in enumerate(cells):
                    pre = "     [" if j == 0 else "      "
                    end = "]" if j == len(cells) - 1 else ","
                    out.append(f"{pre}({fq(p)}, {fq(q)}, {fw(u)}, {fw(v)}){end}")
                out.append("   )")
                out.append("")
        for idx in chunk:
            gi = groups.index(idx)
            out.append(f"/-- Group {gi} of the certificate (parameter cells {idx[0]}–{idx[-1]}). -/")
            out.append(f"def pcellsG{gi} : List VLamCell :=")
            out.append("  [" + ", ".join(f"pcell{i}" for i in idx) + "]")
            out.append("")
        out.append("end ExpAbove")
        out.append("end KnotGame")
        open(f"RequestProject/ExpAboveData{ci}.lean", "w").write("\n".join(out) + "\n")

    out = []
    for ci in range(len(chunks)):
        out.append(f"import RequestProject.ExpAboveData{ci}")
    out.append("")
    out.append("/-!")
    out.append("# Certificate data above the golden ratio (round 10, T32)")
    out.append("")
    out += blurb
    out.append("")
    out.append(f"The data itself is split across `RequestProject.ExpAboveData0` \u2026")
    out.append(f"`RequestProject.ExpAboveData{len(chunks) - 1}`; this file only assembles it.")
    out.append("-/")
    out.append("")
    out.append("namespace KnotGame")
    out.append("namespace ExpAbove")
    out.append("")
    out.append("open KnotGame.ExpVar")
    out.append("")
    out.append(f"/-- The certificate: {len(res)} parameter cells, in increasing order. -/")
    out.append("def pcells : List VLamCell :=")
    out.append("  " + " ++ ".join(f"pcellsG{gi}" for gi in range(len(groups))))
    out.append("")
    out.append("end ExpAbove")
    out.append("end KnotGame")
    open("RequestProject/ExpAboveData.lean", "w").write("\n".join(out) + "\n")

    chk = []
    chk.append("import RequestProject.ExpAboveData")
    chk.append("")
    chk.append("/-!")
    chk.append("# Kernel checks for the certificate above the golden ratio (round 10, T32)")
    chk.append("")
    chk.append("Every check below is a kernel reduction over exact rationals (`decide +kernel`).")
    chk.append(f"The certificate is checked group by group — {len(groups)} groups of at most {G}")
    chk.append("parameter cells — since a single reduction over the whole list does not go")
    chk.append("through.  Generated by `scripts/gen_expabove.py`.")
    chk.append("-/")
    chk.append("")
    chk.append("namespace KnotGame")
    chk.append("namespace ExpAbove")
    chk.append("")
    chk.append("open KnotGame.ExpCert KnotGame.ExpVar")
    chk.append("")
    chk.append("set_option maxHeartbeats 4000000")
    chk.append("")
    chk.append("/-- The return-time bound certified below. -/")
    chk.append(f"abbrev Tbound : ℕ := {used}")
    chk.append("")
    chk.append("/-- The check of one group of parameter cells. -/")
    chk.append(f"abbrev Q : VLamCell → Bool := vlamCellOK ({fq(A)}) ({fq(B)}) Tbound")
    chk.append("")
    chk.append("/-- The parameter cells tile the window. -/")
    chk.append(f"lemma pcells_chained : chained ({fq(L0)}) pcells ({fq(L1)}) = true := by")
    chk.append("  decide +kernel")
    chk.append("")
    for gi in range(len(groups)):
        chk.append(f"lemma pcellsG{gi}_ok : pcellsG{gi}.all Q = true := by decide +kernel")
    chk.append("")
    chk.append("lemma pcells_ok : pcells.all Q = true := by")
    chk.append("  simp only [pcells, List.all_append, " +
               ", ".join(f"pcellsG{gi}_ok" for gi in range(len(groups))) + ", Bool.and_self]")
    chk.append("")
    chk.append("end ExpAbove")
    chk.append("end KnotGame")
    open("RequestProject/ExpAboveChecks.lean", "w").write("\n".join(chk) + "\n")


main()
