"""Generate RequestProject/ExpSharpData.lean: a multiplicity certificate at
lam = 3/2.

Usage:  python3 scripts/gen_expsharp.py T k [a_num a_den b_num b_den]

Each cell of the tiling of J = [a,b] carries `k` distinct branch words of length
`T` whose images (computed exactly, since the parameter is the single point 3/2)
lie again in J.  What is written is checked by the Lean kernel in
RequestProject/ExpSharp.lean; nothing about this program is trusted.
"""
from fractions import Fraction as F
import sys

sys.path.insert(0, "scripts")
from expcert_interval import greedy, fmt_q  # noqa: E402


def main():
    T = int(sys.argv[1])
    k = int(sys.argv[2])
    if len(sys.argv) > 3:
        a = F(int(sys.argv[3]), int(sys.argv[4]))
        b = F(int(sys.argv[5]), int(sys.argv[6]))
    else:
        a, b = F(1, 4), F(3, 4)
    lam = F(3, 2)
    cells = greedy(T, a, b, lam, lam, k=k)
    if cells is None:
        print("no certificate", file=sys.stderr)
        sys.exit(1)
    print(f"-- T = {T}, k = {k}, J = [{a},{b}], {len(cells)} cells", file=sys.stderr)

    out = []
    out.append("import RequestProject.ExpMultiCert")
    out.append("")
    out.append("/-!")
    out.append("# Certificate data for the sharper bound at `lam = 3/2` (round 7)")
    out.append("")
    out.append(f"A multiplicity certificate at `lam = 3/2`: {len(cells)} cells tiling")
    out.append(f"`J = [{a}, {b}]`, each carrying `{k}` distinct branch words of length `{T}`")
    out.append("whose images lie again in `J`.  Generated by `scripts/gen_expsharp.py`; the")
    out.append("checks live in `RequestProject.ExpSharp`.")
    out.append("-/")
    out.append("")
    out.append("namespace KnotGame")
    out.append("namespace ExpSharp")
    out.append("")
    out.append("open KnotGame.ExpMultiCert")
    out.append("")
    out.append("-- The cell list is a large literal; elaborating it exceeds the default budget.")
    out.append("set_option maxHeartbeats 1000000")
    out.append("")
    for i, (p, q, ws) in enumerate(cells):
        body = ", ".join("[" + ",".join(map(str, w)) + "]" for w in ws)
        out.append(f"/-- Cell {i} of the certificate. -/")
        out.append(f"def cell{i} : MCell := ({fmt_q(p)}, {fmt_q(q)}, [{body}])")
        out.append("")
    # The kernel check is run group by group, so the cells are shipped in groups
    # of at most 100 and `cells` is their concatenation.
    G = 100
    groups = [list(range(i, min(i + G, len(cells)))) for i in range(0, len(cells), G)]
    for gi, idx in enumerate(groups):
        out.append(f"/-- Group {gi} of the certificate (cells {idx[0]}–{idx[-1]}). -/")
        out.append(f"def cellsG{gi} : List MCell :=")
        out.append("  [" + ", ".join(f"cell{i}" for i in idx) + "]")
        out.append("")
    out.append(f"/-- The certificate: {len(cells)} cells, each with {k} words of length {T}. -/")
    out.append("def cells : List MCell :=")
    out.append("  " + " ++ ".join(f"cellsG{gi}" for gi in range(len(groups))))
    out.append("")
    out.append("end ExpSharp")
    out.append("end KnotGame")
    open("RequestProject/ExpSharpData.lean", "w").write("\n".join(out) + "\n")


main()
