"""Generate RequestProject/ExpWindowData.lean: a doubling certificate valid
uniformly over the parameter window [1000/667, 8/5], with J = [1/5, 4/5].

The window is split adaptively into parameter cells; on each, interval
arithmetic over lam certifies a list of x-cells (see scripts/expcert_interval.py).
"""
from fractions import Fraction as F
import sys

exec(open('scripts/expcert_interval.py').read().split('if __name__')[0])

a, b = F(1, 5), F(4, 5)
LO, HI = F(1000, 667), F(8, 5)
TS = (6, 7, 8)


def find(l0, l1, depth=0):
    for T in TS:
        c = greedy(T, a, b, l0, l1)
        if c:
            return [(l0, l1, T, c)]
    if depth >= 6:
        return None
    mid = (l0 + l1) / 2
    D = 10 ** 6
    midr = F(int(mid * D), D)
    if l0 < midr < l1:
        mid = midr
    A = find(l0, mid, depth + 1)
    if A is None:
        return None
    B = find(mid, l1, depth + 1)
    if B is None:
        return None
    return A + B


def fq(x):
    return f"{x.numerator}/{x.denominator}" if x.denominator != 1 else f"{x.numerator}"


def fw(w):
    return "[" + ",".join(map(str, w)) + "]"


def main():
    N = 8
    res = []
    for i in range(N):
        D = 10 ** 6
        l0 = LO if i == 0 else F(int((LO + (HI - LO) * F(i, N)) * D), D)
        l1 = HI if i == N - 1 else F(int((LO + (HI - LO) * F(i + 1, N)) * D), D)
        r = find(l0, l1)
        if r is None:
            print("FAILED on", float(l0), float(l1), file=sys.stderr)
            sys.exit(1)
        res += r
        print("done", i, len(r), file=sys.stderr)
        sys.stderr.flush()
    total = sum(len(x[3]) for x in res)
    maxT = max(x[2] for x in res)
    print(f"-- lam-cells: {len(res)}, x-cells: {total}, max T: {maxT}", file=sys.stderr)

    out = []
    out.append("import RequestProject.ExpCert")
    out.append("")
    out.append("/-!")
    out.append("# Certificate data for the parameter window (round 7)")
    out.append("")
    out.append("A doubling certificate for `J = [1/5, 4/5]`, valid uniformly over")
    out.append(f"`lam ∈ [1000/667, 8/5]`: {len(res)} parameter cells carrying {total} interval cells in")
    out.append(f"all, with word length `T ≤ {maxT}`.  Generated by `scripts/gen_expwindow.py`; the")
    out.append("checks live in `RequestProject.ExpWindow`.")
    out.append("-/")
    out.append("")
    out.append("namespace KnotGame")
    out.append("namespace ExpWindow")
    out.append("")
    out.append("open KnotGame.ExpCert")
    out.append("")
    out.append("-- The cell lists are large literals; elaborating them exceeds the default budget.")
    out.append("set_option maxHeartbeats 1000000")
    out.append("")
    out.append("/-- A parameter cell: `(l0, l1, T, cells)`. -/")
    out.append("abbrev LamCell := \u211a \u00d7 \u211a \u00d7 \u2115 \u00d7 List Cell")
    out.append("")

    for i, (l0, l1, T, cells) in enumerate(res):
        out.append(f"/-- Parameter cell {i} of the certificate. -/")
        out.append(f"def lamCell{i} : LamCell :=")
        out.append(f"  ({fq(l0)}, {fq(l1)}, {T},")
        for j, (p, q, ws) in enumerate(cells):
            pre = "     [" if j == 0 else "      "
            end = "]" if j == len(cells) - 1 else ","
            out.append(f"{pre}({fq(p)}, {fq(q)}, {fw(ws[0])}, {fw(ws[1])}){end}")
        out.append("   )")
        out.append("")
    out.append("/-- The certificate: the %d parameter cells, in increasing order. -/" % len(res))
    out.append("def lamCells : List LamCell :=")
    out.append("  [" + ", ".join(f"lamCell{i}" for i in range(len(res))) + "]")
    out.append("")
    out.append("end ExpWindow")
    out.append("end KnotGame")
    open("RequestProject/ExpWindowData.lean", "w").write("\n".join(out) + "\n")


main()
