"""Generate the round-10 T31 certificate at word length 16 (target rate 1.27537).

Usage:  python3 scripts/gen_expsharpest.py [T k [a_num a_den b_num b_den]]

Defaults: `T = 16`, `k = 49`, `J = [1/6, 5/6]`, `lam = 3/2` — 2008 cells, the
largest multiplicity the depth-first search of `scripts/expcert_dfs.py` reaches
at length 16 (50 fails).  The rate is `49 ^ (1/16) = 1.27537…`, improving the
`26 ^ (1/14) = 1.26203…` of `RequestProject.ExpSharper` and round 7's
`15 ^ (1/12) = 1.25316…`.

Writes `RequestProject/ExpSharpestData0.lean` … (the data, split across several
files so that no single file is too large to elaborate) and the umbrella file
`RequestProject/ExpSharpestData.lean`.  The kernel checks and the conclusions
live in `RequestProject/ExpSharpest.lean`, which is not generated.

Nothing about this program is trusted: the Lean kernel re-checks every cell.
"""
from fractions import Fraction as F
import sys

sys.path.insert(0, "scripts")
from expcert_dfs import greedy, fq, fw  # noqa: E402

G = 50   # cells per kernel group
H = 5    # groups per data file


def main():
    T = int(sys.argv[1]) if len(sys.argv) > 1 else 16
    k = int(sys.argv[2]) if len(sys.argv) > 2 else 49
    if len(sys.argv) > 3:
        a = F(int(sys.argv[3]), int(sys.argv[4]))
        b = F(int(sys.argv[5]), int(sys.argv[6]))
    else:
        a, b = F(1, 6), F(5, 6)
    lam = F(3, 2)
    cells = greedy(T, a, b, k, lam, lam)
    if cells is None:
        print("no certificate", file=sys.stderr)
        sys.exit(1)
    groups = [list(range(i, min(i + G, len(cells)))) for i in range(0, len(cells), G)]
    chunks = [groups[i:i + H] for i in range(0, len(groups), H)]
    print(f"-- T = {T}, k = {k}, J = [{a},{b}], {len(cells)} cells, "
          f"{len(groups)} groups, {len(chunks)} files", file=sys.stderr)

    blurb = [
        f"A multiplicity certificate at `lam = 3/2`: {len(cells)} cells tiling",
        f"`J = [{a}, {b}]`, each carrying `{k}` distinct branch words of length `{T}`",
        "whose images lie again in `J`.  Generated by `scripts/gen_expsharpest.py`; the",
        "checks live in `RequestProject.ExpSharpest`.",
    ]

    for ci, chunk in enumerate(chunks):
        lo, hi = chunk[0][0], chunk[-1][-1]
        out = ["import RequestProject.ExpMultiCert", ""]
        out.append("/-!")
        out.append(f"# Certificate data at length 16, part {ci} (round 10, T31)")
        out.append("")
        out += blurb
        out.append("")
        out.append(f"This file carries cells {lo}–{hi}.")
        out.append("-/")
        out.append("")
        out.append("namespace KnotGame")
        out.append("namespace ExpSharpest")
        out.append("")
        out.append("open KnotGame.ExpMultiCert")
        out.append("")
        out.append("-- The cell list is a large literal; elaborating it exceeds the default budget.")
        out.append("set_option maxHeartbeats 4000000")
        out.append("")
        for idx in chunk:
            for i in idx:
                p, q, ws = cells[i]
                body = ", ".join(fw(w) for w in ws)
                out.append(f"/-- Cell {i} of the certificate. -/")
                out.append(f"def cell{i} : MCell := ({fq(p)}, {fq(q)}, [{body}])")
                out.append("")
        for idx in chunk:
            gi = groups.index(idx)
            out.append(f"/-- Group {gi} of the certificate (cells {idx[0]}–{idx[-1]}). -/")
            out.append(f"def cellsG{gi} : List MCell :=")
            out.append("  [" + ", ".join(f"cell{i}" for i in idx) + "]")
            out.append("")
        out.append("end ExpSharpest")
        out.append("end KnotGame")
        open(f"RequestProject/ExpSharpestData{ci}.lean", "w").write("\n".join(out) + "\n")

    out = [f"import RequestProject.ExpSharpestData{ci}" for ci in range(len(chunks))]
    out.append("")
    out.append("/-!")
    out.append("# Certificate data at length 16 (round 10, T31)")
    out.append("")
    out += blurb
    out.append("")
    out.append("The data itself is split across `RequestProject.ExpSharpestData0` …")
    out.append(f"`RequestProject.ExpSharpestData{len(chunks) - 1}`; this file only assembles it.")
    out.append("-/")
    out.append("")
    out.append("namespace KnotGame")
    out.append("namespace ExpSharpest")
    out.append("")
    out.append("open KnotGame.ExpMultiCert")
    out.append("")
    out.append(f"/-- The certificate: {len(cells)} cells, each with {k} words of length {T}. -/")
    out.append("def cells : List MCell :=")
    out.append("  " + " ++ ".join(f"cellsG{gi}" for gi in range(len(groups))))
    out.append("")
    out.append("end ExpSharpest")
    out.append("end KnotGame")
    open("RequestProject/ExpSharpestData.lean", "w").write("\n".join(out) + "\n")

    # The kernel-check skeleton, printed for convenience (not written).
    print("groups:", len(groups), file=sys.stderr)


main()
