#!/usr/bin/env python3
"""Generate the kernel certificate for the reachable configurations at the
plastic number, using *exactly* the packed transition tables of
RequestProject/PlasticIndex.lean.

Writes RequestProject/PlasticCert.lean: a balanced binary-search tree of every
reachable configuration, keyed by the encoding
`enc [] = 0`, `enc (i::c) = (i+1) + 256 * enc c`.  Large subtrees are emitted
as separate definitions so that no single term is unmanageably big.
"""
import re
import sys

SRC = "/workspace/request-project/RequestProject/PlasticIndex.lean"
OUT = "/workspace/request-project/RequestProject/PlasticCert.lean"
HALF = 76
CHUNK = 64


def load_tables():
    txt = open(SRC).read()
    tabs = {}
    for name in ("tabL", "tabM", "tabR"):
        m = re.search(r"def " + name + r" : \u2115 := (\d+)", txt)
        if not m:
            raise SystemExit("table %s not found" % name)
        T = int(m.group(1))
        tabs[name] = [(T >> (8 * i)) % 256 for i in range(153)]
    return tabs


def step(tab, c, is_M):
    out = set()
    for i in c:
        v = tab[i]
        if v != 255:
            out.add(v)
    if is_M:
        out.add(HALF)
    return tuple(sorted(out))


def enc(c):
    k = 0
    for i in reversed(c):
        k = (i + 1) + 256 * k
    return k


HEADER = '''import RequestProject.PlasticTbl

/-!
# The certificate: all reachable configurations at the plastic number

The tree `V` below holds all `%d` configurations of orbit indices reachable at
the plastic number, keyed by `encCfg` and tagged with their breadth-first
depth.  It was produced by a breadth-first
search using the transition tables `tabL`, `tabM`, `tabR` of
`PlasticIndex.lean`; nothing about the way it was produced is trusted, because
`PlasticConfig.lean` checks by kernel computation that the empty configuration
lies in `V`, that `V` is closed under the three moves, and that every member of
`V` has at most seven elements.

The tree is cut into subtrees of at most `%d` nodes, each a separate
definition, so that no single term is unmanageably large.

Generated by `scripts/plastic_cert.py`; do not edit by hand.
-/

namespace KnotGame
namespace Plastic

open Tbl

'''

FOOTER = '''
end Plastic
end KnotGame
'''


def main():
    tabs = load_tables()
    L, M, R = tabs["tabL"], tabs["tabM"], tabs["tabR"]
    moves = [(L, False), (M, True), (R, False)]
    start = ()
    depth = {start: 0}
    parent = {start: (0, ())}
    frontier = [start]
    maxlen = 0
    n = 0
    first = {}
    while frontier:
        nxt = []
        for c in frontier:
            maxlen = max(maxlen, len(c))
            if len(c) not in first:
                first[len(c)] = n
            for mi, (tab, isM) in enumerate(moves):
                d = step(tab, c, isM)
                if d not in depth:
                    depth[d] = n + 1
                    parent[d] = (mi, c)
                    nxt.append(d)
        frontier = nxt
        n += 1
    cfgs = sorted(depth, key=enc)
    print("configs: %d, max knots: %d" % (len(cfgs), maxlen), file=sys.stderr)
    print("first depth attaining k knots: %s"
          % sorted(first.items()), file=sys.stderr)
    keys = [enc(c) for c in cfgs]
    assert len(set(keys)) == len(keys), "encoding not injective on the set"

    defs = []
    counter = [0]

    def nodedata(i):
        c = cfgs[i]
        pm, pc = parent[c]
        return "%d [%s] %d %d [%s]" % (
            enc(c), ",".join(str(j) for j in c), depth[c], pm,
            ",".join(str(j) for j in pc))

    def inline(lo, hi):
        if lo >= hi:
            return "leaf"
        mid = (lo + hi) // 2
        return "(node %s %s %s)" % (nodedata(mid), inline(lo, mid), inline(mid + 1, hi))

    def build(lo, hi):
        if lo >= hi:
            return "leaf"
        if hi - lo <= CHUNK:
            counter[0] += 1
            name = "vsub%d" % counter[0]
            defs.append("private def %s : Tbl := %s\n" % (name, inline(lo, hi)))
            return name
        mid = (lo + hi) // 2
        return "(node %s %s %s)" % (nodedata(mid), build(lo, mid), build(mid + 1, hi))

    top = build(0, len(cfgs))
    body = "".join(defs)
    body += ("\n/-- Every configuration reachable at the plastic number, "
             "as a search tree. -/\ndef V : Tbl := %s\n" % top)
    with open(OUT, "w") as f:
        f.write((HEADER % (len(cfgs), CHUNK)) + body + FOOTER)
    print("wrote %s (%d subtree defs)" % (OUT, len(defs)), file=sys.stderr)


main()
